# Site settings

title: My Blog
description: My Blog

email: blog@gmail.com
baseurl: /blog
url: https://ivayloiv.github.io/blog/

twitter_username: sos
github_username: petrov

future: true
markdown: kramdown
plugins:
  - jekyll-feed

destination: docs

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - docs
  - node_modules
  - scss